# Generated by Django 6.0.6 on 2026-07-08 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='entregeble',
            new_name='Entregable',
        ),
    ]
